#!/usr/bin/python
#
# Utility for managing Cumulus archives.

import os, sys

# Automatically set Python path, based on script directory.  This should be
# removed if the tools are properly installed somewhere.
script_directory = os.path.dirname(sys.argv[0])
sys.path.append(os.path.join(script_directory, 'python'))

import cumulus.cmd_util

cumulus.cmd_util.main(sys.argv)
